"""Type stubs for the compiled Rust extension."""
from typing import Any, Dict, List, Sequence, Tuple

import numpy as np
from numpy.typing import NDArray

__version__: str

class Structure:
    def __init__(
        self,
        matrix: Sequence[Sequence[float]],
        frac_coords: Sequence[Sequence[float]],
        species: Sequence[Dict[str, float]],
    ) -> None: ...
    @staticmethod
    def from_cif(path: str, symprec: float = 1e-4) -> "Structure": ...
    @staticmethod
    def from_cif_str(text: str, symprec: float = 1e-4) -> "Structure": ...
    @staticmethod
    def from_poscar(path: str) -> "Structure": ...
    @staticmethod
    def from_xyz(path: str) -> "Structure": ...
    @staticmethod
    def from_str(text: str, fmt: str, symprec: float = 1e-4) -> "Structure": ...
    @staticmethod
    def available_threads() -> int: ...
    @property
    def n_sites(self) -> int: ...
    @property
    def n_atoms(self) -> float: ...
    @property
    def is_ordered(self) -> bool: ...
    @property
    def volume(self) -> float: ...
    @property
    def elements(self) -> List[str]: ...
    @property
    def composition(self) -> Dict[str, float]: ...
    @property
    def lattice_matrix(self) -> List[List[float]]: ...
    @property
    def frac_coords(self) -> List[List[float]]: ...
    @property
    def cart_coords(self) -> List[List[float]]: ...
    @property
    def species(self) -> List[Dict[str, float]]: ...
    def make_supercell(self, na: int, nb: int, nc: int) -> "Structure": ...
    def prdf(
        self, cutoff: float = 10.0, bin_size: float = 0.1, n_threads: int = 0
    ) -> Tuple[
        NDArray[np.float64],
        Dict[Tuple[str, str], NDArray[np.float64]],
        NDArray[np.float64],
    ]: ...
    def total_rdf(
        self, cutoff: float = 10.0, bin_size: float = 0.1, n_threads: int = 0
    ) -> Tuple[NDArray[np.float64], NDArray[np.float64]]: ...
    def expand_occupancies(
        self, max_sites: int = 4096, seed: int = 42, max_denominator: int = 16
    ) -> Tuple["Structure", Dict[str, Any]]: ...
    def disorder_summary(self) -> List[Dict[str, Any]]: ...
